name: Rebuilding Docker Images

on: 
  push:
    branches:
      - master
    paths: 
      - "**"
      - "!ui/bindata.go"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Setup Go for use with actions
      uses: actions/setup-go@v2
      with:
        go-version: '1.13.8'
    - uses: actions/checkout@v1
    - name: make
      run: |
        mkdir -p $(go env GOPATH)/src/github.com/itpp-labs/
        ln -s $(pwd) $(go env GOPATH)/src/github.com/itpp-labs/hound
        make
    - name: Build and publish DEV Docker Image
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DEV: yes
      with:
        name: itpp-labs/hound/dev
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        buildargs: DEV
    - name: Build and publish Production Docker Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: itpp-labs/hound/production
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # Commiting updates from Github Actions doesn't trigger the action again, so
    # next steps will not be executed twice
    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      name: Commit updates
      with:
        user-name: Marc Demo (from Github Actions)
        user-email: i18n-bot@it-projects.info
        message: |
          :alien: rebuild bindata.go
          
          Sent from Github Actions (see .github/workflows/main.yml )
        #github-token: ${{ secrets.GITHUB_TOKEN }}
